include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    prefer_double_quotes: true
    prefer_single_quotes: false
    public_member_api_docs: false
    cascade_invocations: false
    lines_longer_than_80_chars: false
    
formatter:
  page_width: 90
  trailing_commas: preserve 

analyzer:
  errors:
    invalid_annotation_target: ignore
  plugins:
    - custom_lint